version: '3.9'

services:
  app:
    container_name: node-express-app
    image: node-express-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
